/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse38.main;

import edu.ijse.gdse38.chatControllerImpl.ChatControlerImpl;
import edu.ijse.gdse38.database.PublicChatLogs;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SW96
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    Registry registry;
    private String newDate;
    private ChatControlerImpl chatControlerImpl;

    public Server() {
        initComponents();
        setDate();
        stopButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        viewLogsButton = new javax.swing.JButton();
        noOfUsers = new javax.swing.JLabel();
        usrs = new javax.swing.JLabel();
        onOff = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        chatLabel = new javax.swing.JLabel();
        starButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        serverStatus = new javax.swing.JTextArea();
        message = new javax.swing.JTextField();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewLogsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewLogsButton.setForeground(new java.awt.Color(56, 126, 119));
        viewLogsButton.setText("View Logs");
        viewLogsButton.setBorder(null);
        viewLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLogsButtonActionPerformed(evt);
            }
        });
        mainPanel.add(viewLogsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 110, 30));

        noOfUsers.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        noOfUsers.setForeground(new java.awt.Color(56, 126, 119));
        noOfUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfUsers.setText("0");
        mainPanel.add(noOfUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 80, 30));

        usrs.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        usrs.setForeground(new java.awt.Color(56, 126, 119));
        usrs.setText("Online Users");
        mainPanel.add(usrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        onOff.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        onOff.setForeground(new java.awt.Color(56, 126, 119));
        onOff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        onOff.setText("Off");
        mainPanel.add(onOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 80, 30));

        status.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(56, 126, 119));
        status.setText("Server Status");
        mainPanel.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 30));

        chatLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        chatLabel.setForeground(new java.awt.Color(51, 204, 0));
        chatLabel.setText("Chat Server");
        mainPanel.add(chatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 270, 50));

        starButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        starButton.setForeground(new java.awt.Color(56, 126, 119));
        starButton.setText("Start Server");
        starButton.setBorder(null);
        starButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starButtonActionPerformed(evt);
            }
        });
        mainPanel.add(starButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 110, 30));

        stopButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        stopButton.setForeground(new java.awt.Color(56, 126, 119));
        stopButton.setText("Stop Server");
        stopButton.setBorder(null);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        mainPanel.add(stopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 110, 30));

        serverStatus.setColumns(20);
        serverStatus.setRows(5);
        jScrollPane2.setViewportView(serverStatus);

        mainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 450, 180));

        message.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        message.setText("\"Type Message Here For Clients ...\"");
        message.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        message.setOpaque(false);
        message.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageFocusLost(evt);
            }
        });
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });
        mainPanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 450, 30));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse38/images/StartServer.png"))); // NOI18N
        mainPanel.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void starButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starButtonActionPerformed
        try {
            chatControlerImpl = new ChatControlerImpl(this);
            registry = LocateRegistry.createRegistry(5050);
            registry.rebind("SW", chatControlerImpl);
            stopButton.setEnabled(true);
            onOff.setText("On");
            serverStatus.append("[SERVER STARTED AT " + newDate + "...]\n");
            starButton.setEnabled(false);
        } catch (RemoteException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_starButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        try {
            registry.unbind("SW");
            onOff.setText("Off");
            starButton.setEnabled(true);
            serverStatus.append("[SERVER STOOPED AT " + newDate + "...]\n");
            chatControlerImpl.sendMessage("ALL", "", "[ @ SERVER LOST ", "All");
            UnicastRemoteObject.unexportObject(registry, true);
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            String logs = serverStatus.getText();
            new PublicChatLogs(logs);
            chatControlerImpl.sendMessage("ALL", "", "[ @ SERVER LOST ]", "All");
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void viewLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLogsButtonActionPerformed
        try {
            new PublicChatLogs();
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewLogsButtonActionPerformed

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        try {
            chatControlerImpl.sendMessage("ALL", message.getText() + " ]", "[ @ SERVER ", "All");
            message.setText(null);
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_messageActionPerformed

    private void messageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusGained
        message.setText(null);
    }//GEN-LAST:event_messageFocusGained

    private void messageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFocusLost
        message.setText("Type Message Here For Clients ...");
    }//GEN-LAST:event_messageFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chatLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField message;
    public javax.swing.JLabel noOfUsers;
    private javax.swing.JLabel onOff;
    public javax.swing.JTextArea serverStatus;
    private javax.swing.JButton starButton;
    private javax.swing.JLabel status;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel usrs;
    private javax.swing.JButton viewLogsButton;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = new Date();
        newDate = sdf.format(date);
    }

    public String getDate() {
        return newDate;
    }

}
