/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse38.view;

import edu.ijse.gdse38.connector.ChatConnector;
import edu.ijse.gdse38.controller.ChatController;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author SW96
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setWindow();
        wrongPasswordLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        wrongPasswordLabel = new javax.swing.JLabel();
        wantTOLabel = new javax.swing.JLabel();
        enterToChatLabel = new javax.swing.JLabel();
        chatLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        nameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        logInButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Chat");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wrongPasswordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        wrongPasswordLabel.setForeground(new java.awt.Color(204, 0, 0));
        wrongPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongPasswordLabel.setText("Incorrect Name or Password Check Again !!");
        mainPanel.add(wrongPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 350, 30));

        wantTOLabel.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        wantTOLabel.setForeground(new java.awt.Color(51, 204, 0));
        wantTOLabel.setText("Want to be a Member (click here)");
        wantTOLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wantTOLabelMouseClicked(evt);
            }
        });
        mainPanel.add(wantTOLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 270, 30));

        enterToChatLabel.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        enterToChatLabel.setForeground(new java.awt.Color(0, 51, 51));
        enterToChatLabel.setText("Enter to Chat ...");
        mainPanel.add(enterToChatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        chatLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        chatLabel.setForeground(new java.awt.Color(51, 204, 0));
        chatLabel.setText("Chat");
        mainPanel.add(chatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 50));

        nameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 51, 51));
        nameLabel.setText("User Name");
        mainPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        passwordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 51, 51));
        passwordLabel.setText("Password");
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 30));

        typeLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(0, 51, 51));
        typeLabel.setText("User Type");
        mainPanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        typeCombo.setBackground(new java.awt.Color(93, 150, 140));
        typeCombo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        typeCombo.setForeground(new java.awt.Color(0, 51, 51));
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guest", "Member" }));
        typeCombo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        typeCombo.setOpaque(false);
        typeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboItemStateChanged(evt);
            }
        });
        mainPanel.add(typeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        nameText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 51, 51));
        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.setBorder(null);
        mainPanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 30));

        passwordText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainPanel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 30));

        logInButton.setBackground(new java.awt.Color(0, 102, 0));
        logInButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        logInButton.setForeground(new java.awt.Color(0, 51, 51));
        logInButton.setText("GO NOW");
        logInButton.setOpaque(false);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        mainPanel.add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 90, 30));

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse38/images/login.png"))); // NOI18N
        mainPanel.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void typeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboItemStateChanged
        String type = typeCombo.getSelectedItem().toString();
        if (type.equalsIgnoreCase("Guest")) {
            passwordLabel.setVisible(false);
            passwordText.setVisible(false);
        } else {
            passwordLabel.setVisible(true);
            passwordText.setVisible(true);
        }
    }//GEN-LAST:event_typeComboItemStateChanged

    private void wantTOLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wantTOLabelMouseClicked
        this.dispose();
        new RegisterUser().setVisible(true);
    }//GEN-LAST:event_wantTOLabelMouseClicked

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        String type = typeCombo.getSelectedItem().toString();
        try {
            if (type.equalsIgnoreCase("Guest")) {
                checkGuest(type);
            } else if (type.equalsIgnoreCase("Member")) {
                checkMember(type);
            }
        } catch (RemoteException | NotBoundException | MalformedURLException ex) {
            JOptionPane.showMessageDialog(this, "Server is Offline");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Server is Offline");
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel chatLabel;
    private javax.swing.JLabel enterToChatLabel;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel wantTOLabel;
    private javax.swing.JLabel wrongPasswordLabel;
    // End of variables declaration//GEN-END:variables

    private void setWindow() {
        if (typeCombo.getSelectedItem().toString().equals("Guest")) {
            passwordLabel.setVisible(false);
            passwordText.setVisible(false);
        }
        if (typeCombo.getSelectedItem().toString().equals("Member")) {
            passwordLabel.setVisible(true);
            passwordText.setVisible(true);
        }
    }

    private void checkGuest(String type) throws IOException, NotBoundException {
        String name = nameText.getText();
        ChatController chatController = ChatConnector.getChatConnector().getChatController();
        chatController.checkMemberForRegister(name, "NO");
        /**
         * Check if there is a member like this
         */
        if (!chatController.returnIfAMember(name, "No")) {
            String[] onlineSet = chatController.getOnlineList();
            int count = 0;
            if (onlineSet.length > 0) {
                for (String online : onlineSet) {
                    if (online.equalsIgnoreCase(name)) {
                        count++;
                        break;
                    }
                }
            }
            /**
             * online List Checked and give permission to log in for a guest
             */
            if (count < 1) {
                MainWindow mainWindow = new MainWindow(type, name);
                mainWindow.setVisible(true);
                this.dispose();
            } else {
                wrongPasswordLabel.setVisible(true);
                wrongPasswordLabel.setText("This Name is Currently In Use ! Try New !!");
            }
        } else {
            wrongPasswordLabel.setVisible(true);
            wrongPasswordLabel.setText("This Name is Currently In Use ! Try New !!");
        }
    }

    private void checkMember(String type) throws IOException, NotBoundException {
        String name = nameText.getText();
        char[] pass = passwordText.getPassword();
        String password = String.valueOf(pass);
        ChatController chatController = ChatConnector.getChatConnector().getChatController();
        chatController.checkMemberForLogin(name, password);
        /**
         * If he is a member give the access
         */
        if (chatController.returnIfAMember(name, password)) {
            String[] onlineSet = chatController.getOnlineList();
            int count = 0;
            if (onlineSet.length > 0) {
                for (String online : onlineSet) {
                    if (online.equalsIgnoreCase(name)) {
                        count++;
                        break;
                    }
                }
            }
            /**
             * online List Checked and give permission to log in for a guest
             */
            if (count < 1) {
                MainWindow mainWindow = new MainWindow(type, name);
                this.dispose();
                mainWindow.setVisible(true);
                wrongPasswordLabel.setVisible(false);
            } else {
                wrongPasswordLabel.setVisible(true);
                wrongPasswordLabel.setText("Already Logged !!");
            }
        } else {
            wrongPasswordLabel.setVisible(true);
            wrongPasswordLabel.setText("User Name or Password id Incorrect !!");
        }
    }

}
