/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse38.view;

import edu.ijse.gdse38.connector.ChatConnector;
import edu.ijse.gdse38.controller.ChatController;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SW96
 */
public class RegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
//    private ChatObserverImpl chatObserverImpl;
//    LogIn logIn = new LogIn();
    public RegisterUser() {
        initComponents();
        wrongPasswordLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        wrongPasswordLabel = new javax.swing.JLabel();
        wantTOLabel = new javax.swing.JLabel();
        enterToChatLabel = new javax.swing.JLabel();
        chatLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        logInButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Chat");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wrongPasswordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        wrongPasswordLabel.setForeground(new java.awt.Color(204, 0, 0));
        wrongPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongPasswordLabel.setText("This is already exists. Try another !!!");
        mainPanel.add(wrongPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 30));

        wantTOLabel.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        wantTOLabel.setForeground(new java.awt.Color(51, 204, 0));
        wantTOLabel.setText("Log as a guest (click here)");
        wantTOLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wantTOLabelMouseClicked(evt);
            }
        });
        mainPanel.add(wantTOLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 30));

        enterToChatLabel.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        enterToChatLabel.setForeground(new java.awt.Color(0, 51, 51));
        enterToChatLabel.setText("Register for Member ...");
        mainPanel.add(enterToChatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        chatLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        chatLabel.setForeground(new java.awt.Color(51, 204, 0));
        chatLabel.setText("Chat");
        mainPanel.add(chatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 50));

        nameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 51, 51));
        nameLabel.setText("User Name");
        mainPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        passwordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 51, 51));
        passwordLabel.setText("Password");
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        nameText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(0, 51, 51));
        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.setBorder(null);
        mainPanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 30));

        passwordText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mainPanel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 200, 30));

        logInButton.setBackground(new java.awt.Color(0, 102, 0));
        logInButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        logInButton.setForeground(new java.awt.Color(0, 51, 51));
        logInButton.setText("GO NOW");
        logInButton.setOpaque(false);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        mainPanel.add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 30));

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse38/images/login.png"))); // NOI18N
        mainPanel.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wantTOLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wantTOLabelMouseClicked
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_wantTOLabelMouseClicked

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        try {
            giveAccess();
        } catch (IOException | NotBoundException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel chatLabel;
    private javax.swing.JLabel enterToChatLabel;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel wantTOLabel;
    private javax.swing.JLabel wrongPasswordLabel;
    // End of variables declaration//GEN-END:variables

    private void giveAccess() throws IOException, NotBoundException {
        String name = nameText.getText();
        char[] pass = passwordText.getPassword();
        String password = String.valueOf(pass);
        ChatController chatController = ChatConnector.getChatConnector().getChatController();
        chatController.checkMemberForRegister(name, password);
        /**
         * Check if also is member or not
         */
        if (!chatController.returnIfAMember(name, password)) {

            /**
             * Check if also in online List
             */
            String[] onlineSet = chatController.getOnlineList();
            int count = 0;
            if (onlineSet.length > 0) {
                for (String online : onlineSet) {
                    if (online.equalsIgnoreCase(name)) {
                        count++;
                        break;
                    }
                }
            }
            /**
             * If Conditions are true give the access to Register
             */
            if (count < 1) {
                chatController.addMember(name, password);
                chatController.checkMemberForLogin(name, password);
                if (chatController.returnIfAMember(name, password)) {
                    MainWindow mainWindow = new MainWindow("Member", name);
                    mainWindow.setVisible(true);
                    wrongPasswordLabel.setVisible(false);
                    this.dispose();
                }
            } else {
                wrongPasswordLabel.setVisible(true);
                wrongPasswordLabel.setText("This Name is Currently In Use ! Try New !!");
            }

        } else {
            wrongPasswordLabel.setVisible(true);
        }
    }

}
